tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"

brew "bash"
brew "bat"
brew "cmake"
brew "curl"
brew "elixir"
brew "fzf"
brew "go"
brew "htop"
brew "jq"
brew "node"
brew "ripgrep"
brew "tmux"
brew "vim"
brew "wget"
brew "yarn"

cask "discord"
cask "docker"
cask "google-chrome"
cask "google-cloud-sdk"
cask "iterm2-beta"
cask "logitech-options"
cask "slack"
cask "spotify"
cask "visual-studio-code"
cask "font-fira-code"

